import jax

jax.config.update("jax_enable_x64", True)

from .likelihood import (
    fgn_gamma,
    fgn_covariance,
    noise_covariance,
    displacement_covariance,
    anisotropic_step_covariance,
    anisotropic_displacement_covariance,
)
from .model import (
    normal_diffusion_model,
    anomalous_diffusion_model,
    anisotropic_diffusion_model,
    batched_normal_diffusion_model,
    batched_anomalous_diffusion_model,
    batched_anisotropic_diffusion_model,
)
from .priors import (
    NormalModelPrior,
    AnomalousModelPrior,
    AnisotropicModelPrior,
    WEAK_NORMAL_PRIOR,
    WEAK_ANOMALOUS_PRIOR,
    WEAK_ANISOTROPIC_PRIOR,
    sigma_prior_from_localization,
)
from .inference import (
    MAPFit,
    fit_map,
    sample_posterior,
    sample_posterior_table,
    fit_batch_svi,
    fit_all_tracks,
    fit_batch_map,
)
from .simulate import simulate_fbm_tracks, simulate_anisotropic_tracks
from .bayes_factor import (
    log_bayes_factor_anisotropy,
    batched_log_bayes_factor_anisotropy,
    per_track_log_bayes_factor,
    aggregate_log_bayes_factor,
)
from .viz import (
    samples_dict_to_arrays,
    plot_posterior_corner,
    plot_mcmc_trace,
    plot_estimator_scatter,
    plot_D_alpha_joint,
    plot_D_recovery,
    plot_alpha_recovery,
    plot_bias_vs_D_null,
    plot_log_bf_distribution,
    plot_trajectory_gallery,
    plot_spatial_map,
    plot_eps_vs_log_bf,
    plot_eps_forest,
)

__all__ = [
    "fgn_gamma",
    "fgn_covariance",
    "noise_covariance",
    "displacement_covariance",
    "anisotropic_step_covariance",
    "anisotropic_displacement_covariance",
    "normal_diffusion_model",
    "anomalous_diffusion_model",
    "anisotropic_diffusion_model",
    "batched_normal_diffusion_model",
    "batched_anomalous_diffusion_model",
    "batched_anisotropic_diffusion_model",
    "NormalModelPrior",
    "AnomalousModelPrior",
    "AnisotropicModelPrior",
    "WEAK_NORMAL_PRIOR",
    "WEAK_ANOMALOUS_PRIOR",
    "WEAK_ANISOTROPIC_PRIOR",
    "sigma_prior_from_localization",
    "MAPFit",
    "fit_map",
    "sample_posterior",
    "sample_posterior_table",
    "fit_batch_svi",
    "fit_all_tracks",
    "fit_batch_map",
    "simulate_fbm_tracks",
    "simulate_anisotropic_tracks",
    "log_bayes_factor_anisotropy",
    "batched_log_bayes_factor_anisotropy",
    "per_track_log_bayes_factor",
    "aggregate_log_bayes_factor",
    "samples_dict_to_arrays",
    "plot_posterior_corner",
    "plot_mcmc_trace",
    "plot_estimator_scatter",
    "plot_D_alpha_joint",
    "plot_D_recovery",
    "plot_alpha_recovery",
    "plot_bias_vs_D_null",
    "plot_log_bf_distribution",
    "plot_trajectory_gallery",
    "plot_spatial_map",
    "plot_eps_vs_log_bf",
    "plot_eps_forest",
]
